

<div class="cankle clearfix">
   <div class="cankle-container container" >
      <div class="row">
         <div class="col-sm col-md-6 col-xl-3">
<div class="mx-4">
      <?php 
         require_once('inc/cankle1.inc');
         ?>
            </div><!--mx-4 -->
         </div><!-- / cankle 1-->
         <div class="col-sm col-md-6 col-xl-3">
            <div class="mx-4">
      <?php 
         require_once('inc/cankle2.inc');
         ?>
         </div><!--mx-4 -->
         </div><!-- / cankle 2 -->
         <div class="col-sm col-md-6 col-xl-3">
            <div class="mx-4">
      <?php 
         require_once('inc/cankle3.inc');
         ?>
         </div><!--mx-4 -->
         </div><!-- / cankle 3 -->
         <div class="col-sm col-md-6 col-xl-3">
            <div class="mx-4">
      <?php 
         require_once('inc/cankle4.inc');
         ?>
         </div><!--mx-4 -->
         </div><!-- / cankle 4 -->
      </div><!-- / row -->
   </div><!-- / cankle-container container -->
</div><!-- / cankle clearfix -->
 
				

       

