  

<div class="site-hero-wrap">
    <div class="clearfix">
        <div class="site-hero">
        <div class="region region-hero">
            <img loading="lazy" src="images/Hi-res-Campus-Summer24-7.webp"  height="380" alt="Image of the Library" class="img-fluid image-style-hero">
         </div><!-- /region-hero -->
            <div class="library-logo-wrap container">
                <div class="library-logo position-absolute top-50 translate-middle-y">
                    <a href="index.php">Library</a>
                </div>
        </div><!-- /logo-wrap -->
        </div><!-- /site-hero -->
    </div><!-- /clearfix -->
</div><!-- /row -->
