<div class="justify-content-end">
<div class="libnav">
<nav class="navbar libnav navbar-expand-lg bg-body-tertiary">
   <div class="container d-flex">

			<button class="navbar-toggler campusbutton ms-auto" type="button" data-bs-toggle="offcanvas" data-bs-target="#libNavDropdown" aria-controls="#libNavDropdown"  aria-expanded="false" aria-label="Toggle navigation">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-list" viewBox="0 0 16 16">
                  <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5"/>
                </svg>
                 <span class="icon-text">library</span>
			</button>


		<div class="offcanvas offcanvas-end justify-content-md-end" id="libNavDropdown">
            <div class="offcanvas-header">
              <h5 class="offcanvas-title" id="offcanvasNavbarDarkLabel">Library Menu</h5>
              <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div><!-- /offcanvas-header -->
   <div class="offcanvas-body justify-content-end">
					<ul class="nav navbar-nav justify-content-end">
						<li class="nav-item"><a class="nav-link" href="index.php">Home</a></li>
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false" href="about-library.php" title="">About<span class="caret"></span></a>
							<ul class="dropdown-menu">
                                  <li><a class="dropdown-item" href="about-library.php">About the Library</a></li>
                                  <li><a class="dropdown-item" href="accessibility.php">Accessibility</a></li>
                                  <li><a class="dropdown-item" href="comments.php">Comments</a></li>
                                  <li><a class="dropdown-item" href="hours.php">Hours</a></li>
                                  <li><a class="dropdown-item" href="librarians.php">Librarians</a></li>
                                  <li><a class="dropdown-item" href="https://suny-bcc.primo.exlibrisgroup.com/discovery/collectionDiscovery?vid=01SUNY_BCC%3A01SUNY_BCC&collectionId=81140598290004811">New Books</a></li>
                                  <li><a class="dropdown-item" href="policies.php">Policies</a></li>
                                  <li><a class="dropdown-item" href="https://sunybroome.edu/dept/library/">Staff</a></li>
							</ul>
						</li>
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false" href="about-library.php" title="">Find & Borrow<span class="caret"></span></a>   
							<ul class="dropdown-menu">
								<li><a class="dropdown-item" href="books-and-media.php">Books and Media</a></li>
								<li><a class="dropdown-item" href="databases.php">Databases by Subject</a></li>
								<li><a class="dropdown-item" href="https://sunybroome.libguides.com/az/databases">Databases by Title</a></li>
                                <li><a class="dropdown-item" href="connecting.php">How to connect to databases</a></li>
								<li><a class="dropdown-item" href="interlibraryloan.php">Interlibrary Loan</a></li>
								<li><a class="dropdown-item" href="https://suny-bcc.primo.exlibrisgroup.com/discovery/jsearch?vid=01SUNY_BCC:01SUNY_BCC&lang=en">Journal A-Z List</a></li>
								<li><a class="dropdown-item" href="https://browzine.com/libraries/3957/subjects">Browse Journals and magazines</a></li>
							</ul>
						</li>
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false" href="https://sunybroome.info/library/research-tools" title="">Research Guides<span class="caret"></span></a>
							<ul class="dropdown-menu">
								<li><a class="dropdown-item" href="https://sunybroome.libguides.com/citation-guides/apa-style-guide">APA Style Guide</a></li>
								<li><a class="dropdown-item" href="https://sunybroome.libguides.com/citation-guides/mla-style-guide">MLA Style Guide</a></li>
								<li><a class="dropdown-item" href="course-guides.php">Course Guides</a></li>
								<li><a class="dropdown-item" href="subject-guides.php">Subject Guides</a></li>
								<li><a class="dropdown-item" href="tutorials.php">Tutorials</a></li>
							</ul>
						
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false" href="about-library.php" title="">Services<span class="caret"></span></a>  
							<ul class="dropdown-menu">
								<li><a class="dropdown-item" href="book-librarian.php">Book a Librarian</a></li>
								<li><a class="dropdown-item" href="facultyservices.php">Faculty Support</a></li>
								<li><a class="dropdown-item" href="interlibrary-loan.php">Interlibrary Loan</a></li>
						        <li><a class="dropdown-item" href="oer.php">OER </a></li>
								<li><a class="dropdown-item" href="purchase-request.php">Purchase Request</a></li>
								<li><a class="dropdown-item" href="reserve-study-room.php">Reserve a Study Room</a></li>
								<li><a class="dropdown-item" href="studentservices.php">Student Support</a></li>
								<li><a class="dropdown-item" href="textbooks-reserve.php">Textbooks on Reserve</a></li>
								<li><a class="dropdown-item" href="accounts.php" title="">Your Library Accounts</a></li>
							</ul>
						</li>
						<li class="nav-item"><a class="nav-link" href="help.php">Help</a></li>
					</ul>
       </div><!-- /offcanvas body-->
				</div><!-- /offcanvas -->
</nav>
       </div><!-- /libnav -->
</div><!-- /justify-content-end -->

    <div class="mobile_chat">
<script src="https://sunybroome.libanswers.com/load_chat.php?hash=5a4e12972681f2cc6bfa79be6d9c052bb3c3e0467170d18124beef22247496ea"></script>
        <div id="libchat_5a4e12972681f2cc6bfa79be6d9c052bb3c3e0467170d18124beef22247496ea"></div>
    </div>
