<div id="front-display" class="container clearfix">
	<div class="row">	
		<div id="books-wrapper" class="col-md-6">
			<div class="books-display">
				<div class="region region-books-display">
				<h3 class="block-title">New Books</h3>
			        <div class="item-list">    
						<ul class="list-inline">          
							<li class="list-inline-item">  
					    <div class="views-field views-field-description"> <span class="field-content"><a href="https://suny-bcc.primo.exlibrisgroup.com/discovery/fulldisplay?docid=alma992397240004811&amp;context=U&amp;vid=01SUNY_BCC:01SUNY_BCC&amp;lang=en"><img height="150" alt="The Big Jones cookbook : recipes for savoring the heritage of regional Southern cooking by Fehribach, Paul, author." src="https://syndetics.com/index.php?client=primo&amp;isbn=022620586X/mc.jpg"></a></span>  </div></li>
					            <li class="list-inline-item">  
					    <div class="views-field views-field-description"><span class="field-content"><a href="https://suny-bcc.primo.exlibrisgroup.com/discovery/fulldisplay?docid=alma992397240304811&amp;context=U&amp;vid=01SUNY_BCC:01SUNY_BCC&amp;lang=en"><img height="150" alt="No more police : a case for abolition by Kaba, Mariame, author." src="https://syndetics.com/index.php?client=primo&amp;isbn=1620977303/mc.jpg"></a></span>  </div></li>
					            <li class="list-inline-item">  
					    <div class="views-field views-field-description"><span class="field-content"><a href="https://suny-bcc.primo.exlibrisgroup.com/discovery/fulldisplay?docid=alma992397240104811&amp;context=U&amp;vid=01SUNY_BCC:01SUNY_BCC&amp;lang=en"><img height="150" alt="Essentials of thought leadership &amp; content marketing : boost your brand, increase your market share, and generate qualified leads by Kaplan, Paul, 1972- author." src="https://syndetics.com/index.php?client=primo&amp;isbn=1610353676/mc.jpg"></a></span>  </div></li>
					            <li class="list-inline-item">  
					    <div class="views-field views-field-description"><span class="field-content"><a href="https://suny-bcc.primo.exlibrisgroup.com/discovery/fulldisplay?docid=alma992397240904811&amp;context=U&amp;vid=01SUNY_BCC:01SUNY_BCC&amp;lang=en"><img height="150" alt="Looking at fashion : a guide to terms, styles, and techniques by Mancoff, Debra N., 1950- author." src="https://syndetics.com/index.php?client=primo&amp;isbn=9781606068991/mc.jpg"></a></span></div></li>


							<li class="list-inline-item">  
					    <div class="views-field views-field-description"> <span class="field-content"><a href="https://suny-bcc.primo.exlibrisgroup.com/discovery/fulldisplay?docid=alma992394939804811&amp;context=U&amp;vid=01SUNY_BCC:01SUNY_BCC&amp;lang=en"><img height="150" alt="The climate book : the facts and the solutions by Thunberg, Greta, 2003- compiler." src="https://syndetics.com/index.php?client=primo&amp;isbn=0593492315/mc.jpg"></a></span></div></li>
					            <li class="list-inline-item">  
					    <div class="views-field views-field-description"><span class="field-content"><a href="https://suny-bcc.primo.exlibrisgroup.com/discovery/fulldisplay?docid=alma992397240204811&amp;context=U&amp;vid=01SUNY_BCC:01SUNY_BCC&amp;lang=en"><img height="150" alt="Did That Just Happen?! : Beyond Diversity --Creating Sustainable and Inclusive Organizations. by Pinder-Amaker, Stephanie." src="https://syndetics.com/index.php?client=primo&amp;isbn=0807035890/mc.jpg"></a></span></div><div class="views-field views-field-title"></div></li>
					            <li class="list-inline-item">  
					    <div class="views-field views-field-description"><span class="field-content"><a href="https://suny-bcc.primo.exlibrisgroup.com/discovery/fulldisplay?docid=alma992390340404811&amp;context=U&amp;vid=01SUNY_BCC:01SUNY_BCC&amp;lang=en"><img height="150" alt="Demon Copperhead : a novel by Kingsolver, Barbara, author." src="https://syndetics.com/index.php?client=primo&amp;isbn=0063251922/mc.jpg"></a></span></div><div class="views-field views-field-title"></div></li>
					            <li class="list-inline-item">  
					    <div class="views-field views-field-description"><span class="field-content"><a href="https://suny-bcc.primo.exlibrisgroup.com/discovery/fulldisplay?docid=alma992387240504811&amp;context=U&amp;vid=01SUNY_BCC:01SUNY_BCC&amp;lang=en"><img height="150" alt="Corn dance : inspired First American cuisine by Oden, Loretta Barrett, author." src="https://syndetics.com/index.php?client=primo&amp;isbn=9780806190785/mc.jpg"></a></span></div><div class="views-field views-field-title"></div></li>
					       
 </ul>
</div> 
</div>
					
					<div class="more-link">
					  <a href="https://suny-bcc.primo.exlibrisgroup.com/discovery/collectionDiscovery?vid=01SUNY_BCC%3A01SUNY_BCC&collectionId=81140598290004811">
					    View more new books  </a>
					</div>
				</div><!-- /region -->	
			</div><!-- /books-display -->
		
		<div id="news-wrapper" class="col-md-6">
			<div class="news-display list-group">
				<h3 class="block-title">News</h3>
				  <div class="views-row views-row-1 views-row-odd views-row-first list-group-item d-flex">
                      <div class="news-image-wrap col-2 p-1">  
                            <div class="fakeimg">Fake Image</div>
                       </div> <!-- /news-image-wrap -->
				      <div class="views-field views-field-title col">
                        <span class="field-content"><a href="/library/news/videos-pride-month-available-avon">Videos for PRIDE month available in AVON</a></span>  
                       </div>  <!-- /news-title -->
                   </div><!-- /list-group-item -->
				  
				  <div class="views-row views-row-2 views-row-even list-group-item d-flex">
                      <div class="news-image-wrap col-2 p-1">  
                            <div class="fakeimg">Fake Image</div>
                       </div> <!-- /news-image-wrap -->
				  <div class="views-field views-field-title col"><span class="field-content"><a href="/library/news/scholarly-research-tutorials">Scholarly Research Tutorials </a></span>  </div>  </div>
				 
				  <div class="views-row views-row-3 views-row-odd list-group-item d-flex">
                     <div class="news-image-wrap col-2 p-1">  
                            <div class="fakeimg">Fake Image</div>
                       </div> <!-- /news-image-wrap -->
				  <div class="views-field views-field-title "><span class="field-content"><a href="/library/news/updates-library-services-and-hours">Updates to Library Services and Hours</a></span>  </div>  </div>
				  
				  <div class="views-row views-row-4 views-row-even list-group-item d-flex">
                     <div class="news-image-wrap col-2 p-1">  
                            <div class="fakeimg">Fake Image</div>
                       </div> <!-- /news-image-wrap -->
				  <div class="views-field views-field-title"><span class="field-content"><a href="/library/news/message-library">A Message from the Library</a></span>  </div>  </div>
				  
				<div class="more-link">
				  <a href="/library/news-and-events">
				    View older news  </a>
				</div>
			</div><!-- /news-display -->
		</div><!-- /news wrapper -->
	</div> <!-- /row -->
</div> <!-- /front-display -->
							
