

<h1>Find Books</h1>
   <div class="homepagesearch tabs">    
<div class="tab-content">  
   <form name="searchFormCat" class="input-group input-group-lg"  role="search" id="book-search" method="get" action="https://suny-bcc.primo.exlibrisgroup.com/discovery/search" onsubmit="searchPrimoCat();" enctype="application/x-www-form-urlencoded; charset=utf-8">

            <input type="hidden" name="vid" value="01SUNY_BCC:01SUNY_BCC">
            <input type="hidden" name="tab" value="LibraryCatalog">
            <input type="hidden" name="search_scope" value="MyInstitution">
            <!-- Fixed parameters -->
            <input type="hidden" name="query" id="primoQueryCat">

<div class="input-group input-group-lg">
              <input class="focus form-control" aria-label="Input search terms here" type="text" id="primoQueryCatTemp" placeholder="Search for books and media" value="">
            </div> <!-- col-md-10 -->
            <div class="edit-actions">
              <input type="submit" class="btn btn-info" value="Search" id="go3" title="Search" onclick="searchPrimoCat()" />
            </div><!-- col-md-2 -->
          </form>

          <div class="library-links"><a href="https://suny-bcc.primo.exlibrisgroup.com/discovery/search?&tab=eBooks&search_scope=eBooks&vid=01SUNY_BCC:01SUNY_BCC&offset=0">Search for ebooks</a>, <a href="https://suny-bcc.primo.exlibrisgroup.com/discovery/search?vid=01SUNY_BCC:01SUNY_BCC&sortby=rank&mode=advanced">Advanced Search</a></div>					
</div>
	</div>



