      <div class="order-3 col-12 col-lg-3">

   <div class="region region-sidebar-second">
				



   <nav role="navigation" aria-labelledby="block-b5subtheme-mainmenu-2-menu" id="block-b5subtheme-mainmenu-2" class="block block-menu navigation fourthnav menu--main">
            
  <h5 class="visually-hidden" id="block-b5subtheme-mainmenu-2-menu">Main menu</h5>
  


                      <ul data-block="sidebar_second" class="nav flex-column nav-pills">
                    <li class="nav-item">
                <a href="book-librarian.php" class="nav-link">Book a Librarian</a>
              </li>
                <li class="nav-item menu-item--collapsed">
                <a href="facultyservices.php" class="nav-link">Faculty Services</a>
              </li>
                <li class="nav-item">
                <a href="interlibrary-loan.php" class="nav-link">Interlibrary Loan</a>
              </li>
                <li class="nav-item menu-item--collapsed">
                <a href="oer.php" class="nav-link">Open Educational Resources (OER)</a>
              </li>
                <li class="nav-item">
                <a href="poster-printing-guidelines.php" class="nav-link">Poster Printing Guidelines</a>
              </li>
                <li class="nav-item">
                <a href="purchase-request.php" class="nav-link">Purchase Request</a>
              </li>
                <li class="nav-item">
                <a href="reserve-study-room.php" class="nav-link">Reserve a Study Room</a>
              </li>
                <li class="nav-item">
                <a href="services-alumni-and-visitors.php" class="nav-link">Services for Alumni and Visitors</a>
              </li>
                <li class="nav-item menu-item--collapsed">
                <a href="student-services.php" class="nav-link">Student Services</a>
              </li>
                <li class="nav-item">
                <a href="student-workers.php" class="nav-link">Student Workers</a>
              </li>
                <li class="nav-item">
                <a href="https://sunybroome.edu/gallery/" class="nav-link">SUNY Broome Galleries</a>
              </li>
                <li class="nav-item">
                <a href="your-library-accounts.php" class="nav-link">Your Library Accounts</a>
              </li>
        </ul>
  

  </nav>



			</div>
	


	
	
		</div><!-- sidenav -->
				
           

