      <div class="order-3 col-12 col-lg-3">

   <div class="region region-sidebar-second">
				



   <nav role="navigation" aria-labelledby="block-b5subtheme-mainmenu-2-menu" id="block-b5subtheme-mainmenu-2" class="block block-menu navigation fourthnav menu--main">
            
  <h5 class="visually-hidden" id="block-b5subtheme-mainmenu-2-menu">Main menu</h5>
  
                      <ul data-block="sidebar_second" class="nav flex-column nav-pills">
                    <li class="nav-item">
                <a href="books-and-media.php" class="nav-link">Books and Media</a>
              </li>
                <li class="nav-item">
                <a href="databases.php" class="nav-link">Databases by Subject</a>
              </li>
                <li class="nav-item">
                <a href="https://sunybroome.libguides.com/az/databases" class="nav-link">Databases by Title</a>
              </li>
                <li class="nav-item">
                <a href="connecting.php" class="nav-link">How to connect to databases</a>
              </li>
                <li class="nav-item">
                <a href="interlibrary-loan.php" class="nav-link">Interlibrary Loan</a>
              </li>
                <li class="nav-item">
                <a href="https://suny-bcc.primo.exlibrisgroup.com/discovery/jsearch?vid=01SUNY_BCC:01SUNY_BCC&amp;lang=en" class="nav-link">Journal A-Z List</a>
              </li>
                <li class="nav-item">
                <a href="https://browzine.com/libraries/3957/subjects" title="Search for a particular journal or magazine title" class="nav-link">Browse Journals and Magazines</a>
              </li>
                <li class="nav-item">
                <a href="https://sunybroome.libguides.com/archives" class="nav-link">Archives and Digital Collections</a>
              </li>
        </ul>


  

  </nav>



			</div>
	


	
	
		</div><!-- sidenav -->
				
           

