      <div class="order-3 col-12 col-lg-3">

   <div class="region region-sidebar-second">
				



   <nav role="navigation" aria-labelledby="block-b5subtheme-mainmenu-2-menu" id="block-b5subtheme-mainmenu-2" class="block block-menu navigation fourthnav menu--main">
            
  <h5 class="visually-hidden" id="block-b5subtheme-mainmenu-2-menu">Main menu</h5>
  

                      <ul data-block="sidebar_second" class="nav flex-column nav-pills">
                    <li class="nav-item">
                <a href="about-library.php" title="" class="nav-link nav-link--library-about-library">About the Library</a>
              </li>
                <li class="nav-item menu-item--active-trail">
                <a href="accessibility.php" class="nav-link nav-link--library-accessibility">Accessibility</a>
              </li>
                <li class="nav-item">
                <a href="comments.php" class="nav-link nav-link--library-comments">Comments</a>
              </li>
                <li class="nav-item">
                <a href="hours.php" class="nav-link nav-link--library-hours">Hours</a>
              </li>
                <li class="nav-item">
                <a href="librarians.php" class="nav-link nav-link--library-librarians">Librarians</a>
              </li>
                <li class="nav-item">
                <a href="https://suny-bcc.primo.exlibrisgroup.com/discovery/collectionDiscovery?vid=01SUNY_BCC%3A01SUNY_BCC&amp;collectionId=81140598290004811" class="nav-link nav-link-https--suny-bccprimoexlibrisgroupcom-discovery-collectiondiscoveryvid01suny-bcc3a01suny-bcccollectionid81140598290004811">New Books</a>
              </li>
                <li class="nav-item">
                <a href="policies.php" class="nav-link nav-link--library-policies">Policies</a>
              </li>
                <li class="nav-item">
                <a href="https://sunybroome.edu/dept/library/" class="nav-link nav-link-https--sunybroomeedu-dept-library-">Staff List</a>
              </li>
        </ul>
  

  </nav>



			</div>
	


	
	
		</div><!-- sidenav -->
				
           

