 <div class="order-3 col-12 col-lg-3">
				   <div class="region region-sidebar-second">
	            <div class="hours-block">
	                <h3 class="block-title">Today's Hours</h3>
	                <div id="api_hours_today_iid5196_lid0"></div>
                    <script src="https://sunybroome.libcal.com/api_hours_today.php?iid=5196&lid=0&format=js&systemTime=0&context=object"> </script>
	                <div class="s-lc-w-today-view-all"><a href="hours.php" class="s-lc-w-today-view-link">View all Hours</a></div>
	            </div><!-- hours -->
			</div>	
		</div><!-- sidenav -->
 
