        <aside class="col-sm-3 sidenav region-sidebar-second" role="complementary">
				<section>



   <nav role="navigation" aria-labelledby="block-b5subtheme-mainmenu-2-menu" id="block-b5subtheme-mainmenu-2" class="block block-menu navigation fourthnav menu--main">
            
  <h5 class="visually-hidden" id="block-b5subtheme-mainmenu-2-menu">Main menu</h5>
  

                      <ul data-block="sidebar_second" class="nav flex-column nav-pills">
                    <li class="nav-item">
                <a href="/library/about-library" title="" class="nav-link nav-link--library-about-library" data-drupal-link-system-path="node/123">About the Library</a>
              </li>
                <li class="nav-item menu-item--active-trail">
                <a href="/library/accessibility" class="nav-link nav-link--library-accessibility" data-drupal-link-system-path="node/877">Accessibility</a>
              </li>
                <li class="nav-item">
                <a href="/library/comments" class="nav-link nav-link--library-comments" data-drupal-link-system-path="node/885">Comments</a>
              </li>
                <li class="nav-item">
                <a href="/library/hours" class="nav-link nav-link--library-hours" data-drupal-link-system-path="node/117">Hours</a>
              </li>
                <li class="nav-item">
                <a href="/library/librarians" class="nav-link nav-link--library-librarians" data-drupal-link-system-path="node/1210">Librarians</a>
              </li>
                <li class="nav-item">
                <a href="https://suny-bcc.primo.exlibrisgroup.com/discovery/collectionDiscovery?vid=01SUNY_BCC%3A01SUNY_BCC&amp;collectionId=81140598290004811" class="nav-link nav-link-https--suny-bccprimoexlibrisgroupcom-discovery-collectiondiscoveryvid01suny-bcc3a01suny-bcccollectionid81140598290004811">New Books</a>
              </li>
                <li class="nav-item">
                <a href="/library/policies" class="nav-link nav-link--library-policies" data-drupal-link-system-path="node/1076">Policies</a>
              </li>
                <li class="nav-item">
                <a href="https://sunybroome.edu/dept/library/" class="nav-link nav-link-https--sunybroomeedu-dept-library-">Staff List</a>
              </li>
        </ul>
  

  </nav>



			</section>
	


	
	
		</aside><!-- sidenav -->
				
           

