<div class="secondnav">

    <nav class="navbar campusnav">
<div class="container">
           <div class="region region-branding">
              <a class="navbar-brand" href="https://broome-bs1.ddev.site/"><img src="images/sunybroome-words_retina.png" alt="SUNY Broome Logo" height="27" width="250"></a> 
           </div><!-- /campuslogo -->


           <button class="navbar-toggle campusbutton" type="button" data-toggle="collapse" data-target="#campusNavDropdown" aria-controls="campusNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
           <span class="icon material-icons-sharp">menu</span>
           <span class="icon-text">campus</span>
           </button>

           <div class="collapse navbar-collapse campusnav-links"  id="campusNavDropdown" aria-labelledby="campusNavDropdown">
              <ul class="nav navbar-nav">
                 <li class="nav-item"><a class="nav-link" href="https://broome1.wpenginepowered.com/academics-programs/">Academics &amp; Programs</a></li>
                 <li class="nav-item"><a class="nav-link" href="https://broome1.wpenginepowered.com/admissions-costs/">Admissions &amp; Costs</a></li>
                 <li class="nav-item"><a class="nav-link" href="https://broome1.wpenginepowered.com/our-campus/">Our Campus</a></li>
                 <li class="nav-item"><a class="nav-link" href="https://broome1.wpenginepowered.com/about/">About</a></li>
                 <li class="nav-item"><a class="nav-link" href="https://broome1.wpenginepowered.com/careers-workforce/">Careers &amp; Workforce</a></li>
                 <li class="nav-item"><a class="nav-link" href="https://broome1.wpenginepowered.com/community-alumni/">Foundation &amp; Alumni</a></li>
                 <!--   <li class="nav-item"><a class="nav-link" href="https://broome1.wpenginepowered.com/apply/">Apply Now</a></li> -->
              </ul>
           </div><!-- /collapse -->
       </div><!-- /container -->
    </nav><!-- /campusnav -->
       </div><!-- /container -->
</div><!-- secondnav-->
