			<button class="navbar-toggle campusbutton" type="button" data-toggle="collapse" data-target="#libNavDropdown" aria-controls="#libNavDropdown"  aria-expanded="false" aria-label="Toggle navigation">
			        <span class="icon material-icons-sharp">menu</span>
                    <span class="icon-text">library</span>
			</button>


				<div class="navbar-collapse collapse justify-content-end" id="libNavDropdown">
					<ul class="nav navbar-nav">
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false" href="about-library.php" title="">About Us<span class="caret"></span></a>
							<ul class="dropdown-menu">
                                  <li><a class="dropdown-item" href="https://sunybroome.info/library/about-library">About the Library</a></li>
                                  <li><a class="dropdown-item" href="https://sunybroome.info/library/accessibility">Accessibility</a></li>
                                  <li><a class="dropdown-item" href="https://sunybroome.info/library/comments">Comments</a></li>
                                  <li><a class="dropdown-item" href="https://sunybroome.info/library/contact-us">Contact Us</a></li>
                                  <li><a class="dropdown-item" href="https://sunybroome.info/library/equipment-and-facilities">Equipment and Facilities</a></li>
                                  <li><a class="dropdown-item" href="https://sunybroome.info/library/hours">Hours</a></li>
                                  <li><a class="dropdown-item" href="https://sunybroome.info/library/librarians">Librarians</a></li>
                                  <li><a class="dropdown-item" href="https://sunybroome.info/library/directions">Location and Directions</a></li>
                                  <li><a class="dropdown-item" href="https://sunybroome.info/library/new-books">New Books</a></li>
                                  <li><a class="dropdown-item" href="https://sunybroome.info/library/policies">Policies</a></li>
                                  <li><a class="dropdown-item" href="https://sunybroome.info/library/staff-list">Staff</a></li>
							</ul>
						</li>
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false" href="about-library.php" title="">Find & Borrow<span class="caret"></span></a>   
							<ul class="dropdown-menu">
								<li><a class="dropdown-item" href="https://sunybroome.info/library/databases" title="">Articles by Subject</a></li>
								<li><a class="dropdown-item" href="https://sunybroome.info/library/books-and-media" title="">Books and Media</a></li>
								<li><a class="dropdown-item" href="https://sunybroome.info/library/databases-by-title" title="">Database A-Z</a></li>
								<li><a class="dropdown-item" href="https://sunybroome.info/library/interlibrary-loan" title="">Interlibrary Loan</a></li>
								<li><a class="dropdown-item" href="https://sunybroome.info/library/journals-and-magazines" title="">Journal A-Z </a></li>
							</ul>
						</li>
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false" href="https://sunybroome.info/library/research-tools" title="">Library Guides<span class="caret"></span></a>
							<ul class="dropdown-menu">
								<li><a class="dropdown-item" href="#">APA Style Guide</a></li>
								<li><a class="dropdown-item" href="#">MLA Style Guide</a></li>
								<li><a class="dropdown-item" href="#">Chicago Style Template</a></li>
								<li><a class="dropdown-item" href="#">Course Guides</a></li>
								<li><a class="dropdown-item" href="#">Subject Guides</a></li>
							</ul>
						<li class="nav-item"><a class="nav-link" href="https://sunybroome.info/library/news-and-events">News & Events</a></li>

						
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false" href="about-library.php" title="">Services<span class="caret"></span></a>  
							<ul class="dropdown-menu">
								<li><a class="dropdown-item" href="https://sunybroome.info/library/book-librarian" title="">Book a Librarian</a></li>
								<li><a class="dropdown-item" href="https://sunybroome.info/library/faculty-support" title="">Faculty Support</a></li>
								<li><a class="dropdown-item" href="https://sunybroome.info/library/interlibrary-loan" title="">Interlibrary Loan</a></li>
						        <li><a class="dropdown-item" href="https://sunybroome.info/library/oer/oer-home.php" title="Open Educational Resources">OER </a></li>
								<li><a class="dropdown-item" href="https://sunybroome.info/library/purchase-request" title="">Purchase Request</a></li>
								<li><a class="dropdown-item" href="https://sunybroome.info/library/reserve-study-room" title="">Reserve a Study Room</a></li>
								<li><a class="dropdown-item" href="https://sunybroome.info/library/textbooks-reserve" title="Textbooks and articles on Reserve">Textbooks on Reserve</a></li>
								<li><a class="dropdown-item" href="https://sunybroome.info/library/accounts" title="">Your Library Accounts</a></li>
							</ul>
						</li>
						<li class="nav-item"><a class="nav-link" href="https://sunybroome.info/library/help.php">Need Help?</a></li>
						<li class="nav-item"><a class="nav-link" href="index.php">V1</a></li>
						<li class="nav-item"><a class="nav-link" href="indexv2.php">V2</a></li>
					</ul>
				</div><!-- /navbar-collaspe -->
</nav>

