<style>
.library-logo-bar img { height: 35px;  } 
</style>


<div class="justify-content-end">
<div class="libnav thirdnav">
<nav class="navbar libnav navbar-expand-lg">
   <div class="container d-flex">

         <div class="library-logo-bar region region-branding">
                 <a class="navbar-brand" href="https://www.sunybroome.edu/library/"><img class="img-fluid" src="images/library-logo-blackv2.webp" alt="Library Logo" height="35" ></a> 
		</div><!-- library-logo-bar -->

			<button class="navbar-toggler campusbutton ms-auto" type="button" data-bs-toggle="offcanvas" data-bs-target="#libNavDropdown" aria-controls="#libNavDropdown"  aria-expanded="false" aria-label="Toggle navigation">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-list" viewBox="0 0 16 16">
                  <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5"/>
                </svg>
                 <span class="icon-text">library</span>
			</button>


		<div class="offcanvas offcanvas-end justify-content-md-end" id="libNavDropdown" aria-labelledby="libNavDropdown">
            <div class="offcanvas-header">
              <h5 class="offcanvas-title" id="offcanvasNavbarDarkLabel">Library Menu</h5>
              <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div><!-- /offcanvas-header -->

   <div class="offcanvas-body justify-content-end">
					<ul class="nav navbar-nav justify-content-end">
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false" href="about-library.php" title="">About Us<span class="caret"></span></a>
							<ul class="dropdown-menu">
                                  <li><a  class="dropdown-item" href="https://sunybroome.info/library/about-library">About the Library</a></li>
                                  <li><a  class="dropdown-item" href="https://sunybroome.info/library/accessibility">Accessibility</a></li>
                                  <li><a  class="dropdown-item" href="https://sunybroome.info/library/comments">Comments</a></li>
                                  <li><a  class="dropdown-item" href="https://sunybroome.info/library/contact-us">Contact Us</a></li>
                                  <li><a  class="dropdown-item" href="https://sunybroome.info/library/equipment-and-facilities">Equipment and Facilities</a></li>
                                  <li><a  class="dropdown-item" href="https://sunybroome.info/library/hours">Hours</a></li>
                                  <li><a  class="dropdown-item" href="https://sunybroome.info/library/librarians">Librarians</a></li>
                                  <li><a  class="dropdown-item" href="https://sunybroome.info/library/directions">Location and Directions</a></li>
                                  <li><a  class="dropdown-item" href="https://sunybroome.info/library/new-books">New Books</a></li>
                                  <li><a  class="dropdown-item" href="https://sunybroome.info/library/policies">Policies</a></li>
                                  <li><a  class="dropdown-item" href="https://sunybroome.info/library/staff-list">Staff</a></li>
							</ul>
						</li>
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false" href="about-library.php" title="">Find & Borrow<span class="caret"></span></a>   
							<ul class="dropdown-menu">
								<li><a  class="dropdown-item" href="https://sunybroome.info/library/databases" title="">Articles by Subject</a></li>
								<li><a  class="dropdown-item" href="https://sunybroome.info/library/books-and-media" title="">Books and Media</a></li>
								<li><a  class="dropdown-item" href="https://sunybroome.info/library/databases-by-title" title="">Database A-Z</a></li>
								<li><a  class="dropdown-item" href="https://sunybroome.info/library/interlibrary-loan" title="">Interlibrary Loan</a></li>
								<li><a  class="dropdown-item" href="https://sunybroome.info/library/journals-and-magazines" title="">Journal A-Z </a></li>
							</ul>
						</li>
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false" href="https://sunybroome.info/library/research-tools" title="">Library Guides<span class="caret"></span></a>
							<ul class="dropdown-menu">
								<li><a  class="dropdown-item" href="#">APA Style Guide</a></li>
								<li><a  class="dropdown-item" href="#">MLA Style Guide</a></li>
								<li><a  class="dropdown-item" href="#">Chicago Style Template</a></li>
								<li><a  class="dropdown-item" href="#">Course Guides</a></li>
								<li><a  class="dropdown-item" href="#">Subject Guides</a></li>
							</ul>
						<li class="nav-item"><a class="nav-link" href="https://sunybroome.info/library/news-and-events">News & Events</a></li>

						
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false" href="about-library.php" title="">Services<span class="caret"></span></a>  
							<ul class="dropdown-menu">
								<li><a  class="dropdown-item" href="https://sunybroome.info/library/book-librarian" title="">Book a Librarian</a></li>
								<li><a  class="dropdown-item" href="https://sunybroome.info/library/facultyservices" title="">Faculty Support</a></li>
								<li><a  class="dropdown-item" href="https://sunybroome.info/library/interlibrary-loan" title="">Interlibrary Loan</a></li>
						        <li><a  class="dropdown-item" href="https://sunybroome.info/library/oer/oer-home" title="Open Educational Resources">OER </a></li>
								<li><a  class="dropdown-item" href="https://sunybroome.info/library/purchase-request" title="">Purchase Request</a></li>
								<li><a  class="dropdown-item" href="https://sunybroome.info/library/reserve-study-room" title="">Reserve a Study Room</a></li>
								<li><a  class="dropdown-item" href="https://sunybroome.info/library/textbooks-reserve" title="Textbooks and articles on Reserve">Textbooks on Reserve</a></li>
								<li><a  class="dropdown-item" href="https://sunybroome.info/library/accounts" title="">Your Library Accounts</a></li>
							</ul>
						</li>
						<li class="nav-item"><a class="nav-link" href="https://sunybroome.info/library/help">Need Help?</a></li>
					</ul>
       </div><!-- /offcanvas body-->
				</div><!-- /offcanvas -->
</div><!-- /offcanvas -->
</nav>
       </div><!-- /libnav -->
</div><!-- /justify-content-end -->
