<div class="thirdnav secondnav">
    <nav class="navbar libnav navbar-expand-lg bg-body-tertiary">
       <div class="container">
            <div class="navbar-header">
			            <button type="button" class="navbar-toggle collapsed campusbutton ms-auto" data-toggle="collapse" data-target="#libNavDropdown" aria-expanded="false">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-list" viewBox="0 0 16 16">
                              <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5"/>
                            </svg>
                             <span class="icon-text">library</span>
			            </button>

                             <a class="navbar-brand" href="https://www.sunybroome.edu/library/"><img class="img-fluid" src="images/library-logo-blackv2.webp" alt="Library Logo" height="35" ></a> 

               </div> <!-- /navbar-header -->

		    <div class="navbar-collapse collapse navbar-right" id="libNavDropdown">
			    <ul class="nav navbar-nav">
				    <li class="nav-item"><a class="nav-link" href="https://sunybroome.info/library/about-library" title="">About</a></li>
				    <li class="nav-item"><a class="nav-link" href="https://sunybroome.info/library/find-borrow" title="">Find & Borrow</a></li>
				    <li class="nav-item"><a class="nav-link" href="https://sunybroome.info/library/research-guides" title="">Research Guides</a>
				    <li class="nav-item"><a class="nav-link" href="https://sunybroome.info/library/news-and-events">News & Events</a></li>
				    <li class="nav-item"><a class="nav-link" href="https://sunybroome.info/library/services" title="">Services</a></li>
				    <li class="nav-item"><a class="nav-link" href="https://sunybroome.info/library/help.php">Need Help?</a></li>
			    </ul>
		    </div><!-- /navbar-collaspe -->
    </nav>
</div><!-- /thirdnav -->
