<div class="firstnav">


    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container">

          <div class="navbar-header">
           <button type="button" class="navbar-toggle collapsed campusbutton ms-auto" data-toggle="collapse" data-target="#campuslinksNavDropdown" aria-expanded="false">



                 <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-three-dots" viewBox="0 0 16 16">
                  <path d="M3 9.5a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3m5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3m5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3"/>
                </svg>
                 <span class="icon-text">campus</span>
             </button>


            <a class="navbar-brand" href="https://sunybroome.edu"><img src="images/SB-Wordmark_Gold.png" alt="SUNY Broome Logo" height="27" width="250"></a> 


        </div> <!-- /navbar-header -->




      <div class="collapse navbar-collapse navbar-right" id="campuslinksNavDropdown">
         <ul class="nav navbar-nav">

            <li class="nav-item dropdown">
               <a class="nav-link dropdown-toggle" href="https://sunybroome.edu" role="button" data-toggle="dropdown" aria-expanded="false">
               Campus Menu<span class="caret"></span></a>
               <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="https://sunybroome.edu/academics-programs/">Academics &amp; Programs</a></li>
                  <li><a class="dropdown-item" href="https://sunybroome.edu/admissions-costs/">Admissions &amp; Costs</a> </li>
                  <li><a class="dropdown-item" href="https://sunybroome.edu/our-campus/">Our Campus</a></li>
                  <li><a class="dropdown-item" href="https://sunybroome.edu/about/">About</a></li>
                  <li><a class="dropdown-item" href="https://sunybroome.edu/careers-workforce/">Careers &amp; Workforce</a></li>
                  <li><a class="dropdown-item" href="https://sunybroome.edu/community-alumni/">Foundation &amp; Alumni</a></li>
               </ul>
            </li>
            <li class="nav-item"><a class="nav-link" href="https://sunybroome.edu/directory/">Directory</a></li>
            <li class="nav-item dropdown">
               <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
               Calendar<span class="caret"></span></a>
               <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="https://sunybroome.edu/calendar/">Calendar</a> </li>
                  <li><a class="dropdown-item" href="https://news.sunybroome.edu/calendar/events/list/?tribe_eventcategory%5B0%5D=317">Academic Calendar</a></li>
                  <li><a class="dropdown-item" href="https://news.sunybroome.edu/calendar/events/">Events Calendar</a></li>
                  <li><a class="dropdown-item" href="https://sunybroome.edu/registrar/college-academic-calendar/">Key Dates</a></li>
               </ul>
            </li>
            <li class="nav-item dropdown">
               <a class="nav-link dropdown-toggle" href="https://sunybroome.edu/news/" role="button" data-toggle="dropdown" aria-expanded="false">
               News<span class="caret"></span></a>
               <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="https://sunybroome.edu/news/">News</a> </li>
                  <li><a class="dropdown-item" href="https://news.sunybroome.edu/buzz/">Buzz</a></li>
                  <li><a class="dropdown-item" href="https://news.sunybroome.edu/buzz/category/hivehq/">HiveHQ</a></li>
               </ul>
            </li>
            <li class="nav-item"><a class="nav-link" href="https://mycollege.sunybroome.edu">MyCollege</a></li>
         </ul>
      </div><!-- /navbar-collapse -->

   </div><!-- /container -->
</nav> 
   
</div><!-- /firstnav -->
